#!/usr/bin/python3
# =============================================================================
# Author: Ashkan Mirzaee
# License: GPL-3.0
# Date: 2021/07/13
# Source: https://github.com/ashki23/stool
# =============================================================================

import os
import sys
import argparse

parser = argparse.ArgumentParser(description = 'Running and stopping an ssh-agent on a host')
parser.add_argument('-s', action = 'store_true', help = 'start an agent on the current host')
parser.add_argument('-k', action = 'store_true', help = 'Kill the current agent on the host')
parser.add_argument('-l', action = 'store_true', help = 'List the current agent on the host')
args = parser.parse_args()

if len(sys.argv) == 1:
    parser.print_help(sys.stderr)
    sys.exit(1)

if args.s:
    os.system("""
    if [ -f ~/.ssh/id_rsa ]; then
    if ! ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
    echo "Starting an agent on $(hostname) ..."
    install -d /home/$USER/.ssh_auth
    eval `ssh-agent -s`
    ssh-add
    echo $SSH_AUTH_SOCK > /home/$USER/.ssh_auth/$(hostname)
    if ! grep -q SSH_AUTH_SOCK /home/$USER/.bashrc; then
    echo "
# >>> ssh-agent >>>
if [ -f /home/$USER/.ssh_auth/\$(hostname) ]; then
export SSH_AUTH_SOCK=\`cat /home/$USER/.ssh_auth/\$(hostname)\`
fi
# <<< ssh-agent <<<
" >> /home/$USER/.bashrc
    fi
    echo "The ssh-agent authentication is added to ~/.bashrc. Run 'source ~/.bashrc' to apply the changes."
    else
    if [ -z $SSH_AUTH_SOCK ]; then
    echo "An agent is running but the authentication is not available. Stop the agent with -k and rerun the command."
    fi
    echo "The ssh-agent is running on $(hostname)."
    fi
    else
    echo "SSH keys not found. Add your id_rsa keys to '~/.ssh'."
    fi
    """)

if args.k:
    os.system("""
    if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
    echo "Stopping the current agent on $(hostname) ..."
    kill `ps -elf | grep ssh-agent | grep -v grep | grep $USER | awk '{print $4}'`
    rm -f /home/$USER/.ssh_auth/$(hostname)
    else
    echo "No running agent found on $(hostname)."
    fi
    """)

if args.l:
    os.system("""
    if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
    ps -elf | grep ssh-agent | grep -v grep | grep $USER
    else
    echo "No running agent found on $(hostname)."
    fi
    """)
