.SH AUTHOR
Ashkan Mirzaee: https://ashki23.github.io/
.SH INTERNET RESOURCES
.br
Documentation:  https://sbox.readthedocs.io/
.br
Downloads:  https://github.com/ashki23/sbox/releases/latest
.br
Module repository:  https://github.com/ashki23/sbox

.SH LICENSING
Sbox is distributed under an Open Source license. See the file
"LICENSE" in the source distribution for information on terms &
conditions for accessing and otherwise using Sbox and for a
DISCLAIMER OF ALL WARRANTIES.
